name: $name
version: $version
main: $main
api-version: "$apiVersion"
website: https://github.com/PfauMC/bluemap-folia-regions
authors:
  - andreypfau
folia-supported: true
dependencies:
  server:
    BlueMap:
      load: AFTER
      required: true
